version: '3.1'

services:
  drupal:
    image: drupal
    ports: 
      - "8080:80"
    volumes: # info on volumes here : https://hub.docker.com/_/drupal/
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  db:
    image: postgres 
    environment: 
      POSTGRES_PASSWORD: postgres

# specifies named volumes can be empty
# check : https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: